### ISSUE TITLE
Handle "Unable to parse site url"

### ISSUE THREAD

**Issue by ifel** [mgrybyk/uasword#3]
My instance died in the middle of the night with the exception below until I found it's dead (several hours).

I believe the script reloads the urls periodically, furthermore, it uses more than one list. So it would nice, if instead of failing, it would ignore the failure, print out a warning and keep working. If the list of targets is empty (none was loaded) it would just sleep until target lists reload.

One more thing, it seems there are no retries, it would be nice to have some.

IDK what was the content of the file, you can trace it by the timestamp, the timestamp is in UTC.

```
2022-03-20T14:07:17.526Z WARN: Failed to fetch new urls list from https://raw.githubusercontent.com/mgrybyk/uasword/master/data/sites.json
/home/ubuntu/uasword/main.js:153
        throw new Error('Unable to parse site url', sitesUrl)
              ^

Error: Unable to parse site url
    at getSitesFn (/home/ubuntu/uasword/main.js:153:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at getSites (/home/ubuntu/uasword/main.js:128:9)
    at Timeout._onTimeout (/home/ubuntu/uasword/main.js:35:28)
```

**Comment by mgrybyk** [comment]
Fixed with e36ef78a7dc95dd56df9907c1ff23446c2416b8e
